prp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
import library.urls as library_urls
from user import urls as user_urls
from .views import redirect_root
from library.views import json

from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm


urlpatterns = [
  url(r'^$', redirect_root),
  url(r'^library/', include(library_urls)),
  url(r'^admin/', admin.site.urls),
  url(r'^index/$', json),
  url(r'^user/', include(user_urls, namespace='dj-auth')),
  


]

    

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .views import signup
app_name = 'user'

password_urls = [
    url(r'^change/$',
        auth_views.password_change,
        {'template_name': 'user/password_change_form.html',
        'post_change_redirect': reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name': 'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$', auth_views.password_reset,
        {'template_name': 
            'user/password_reset_form.html',
        'email_template_name':
            'user/password_reset_email.txt',
        'subject_template_name':
            'user/password_reset_subject.txt',
        'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
     url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'^reset/done/$',
        auth_views.password_reset_complete,
            {'template_name':
                'user/password_reset_complete.html',
            'extra_context':
                {'form': AuthenticationForm}},
            name='pw_reset_complete'),

]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    
    url(r'^login/$', auth_views.login,
        {'template_name': 'user/login.html'},
        name='login'),
    
   url(r'^logout/$',
        auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
        
    url(r'^password/', include(password_urls)),
    
    url(r'^create/$', signup,
        name='create'),
    
        
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
'''
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.contrib.auth import get_user_model
from .utils import ActivationMailFormMixin

class UserCreationForm(ActivationMailFormMixin, UserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email')

    mail_validation_error = 'User created. Could not send activation email. Please try again later.'
    
    def save(self, **kwargs):
        
'''

user/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            contributors = Group.objects.get(name='contributor')
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            user.groups.add(contributors)
            login(request, user)
            return redirect('library_book_list')
    else:
        form = UserCreationForm()
    return render(request, 'user/signup.html', {'form': form})

user/templates/user/base_user.html
{% extends parent_template|default:"base.html" %}

user/templates/user/logged_out.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Logged Out
{% endblock %}

{% block content %}
  <div class="container"
      <p>You've successfully logged out.</p>
      {% include "user/login_form.html" with login_button='Log Back In' %}
  </div>
{% endblock %}

user/templates/user/login.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Login
{% endblock %}

{% block content %}
  <div class="container">
      {% include "user/login_form.html" %}
  
  
    
      <ul class="task-list">
        <li><a href="{% url 'dj-auth:pw_reset_start' %}">
           Forgotten password?         
          </a></li>
      </ul>
    </div>
  
  
  </div>



{% endblock %}

user/templates/user/login_form.html
{% load bootstrap %}
<div class="container">
<form
    action="{% url 'dj-auth:login' %}"
    method="post">
  {% csrf_token %}
  {{ form|bootstrap }}
  
  {% if next %}
  <input type="hidden"
         name="next"
         value="{{ next }}">
{% endif %}
  
  <button type="submit">
    {{ login_button|default:'Log in' }}</button>
</form>


</div>

user/templates/user/password_change_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}

   <p> Password succesfully changed.</p>
   
   
{% endblock %}

user/templates/user/password_change_form.html
{% extends parent_template|default:"user/base_user.html" %}
{% load bootstrap %}
{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
<div class="container">
  <form action="{% url 'dj-auth:pw_change' %}" 
      method="post">
   {% csrf_token %}
   {{ form|bootstrap }}
   <button type="submit">
     Change Password</button>
  </form>
</div>
{% endblock %}

user/templates/user/password_reset.sent.html
{% extends parent_template|default:"user/base_user.html" %}
{% block title %}
{{ block.super }} - Password Reset Sent
{% endblock %}

{% block content %}
  <div class="row">
      <p> Password reset email sent!></p>
      <p> Please check your inbox and spam box.</p>
  </div>

{% endblock %}

user/templates/user/password_reset_complete.html
{% extends parent_template|default:"user/base_user.html" %}
{% block title %}
{{ block.super }} - Password Reset Successful 
{% endblock %}

{% block content %}
  <div class="container">
   <p> Your password has been reset. </p>
   <p> Login in below using your new password.</p>
   {% inlude "user/login_form.html" %}
  </div>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends parent_template|default:"user/base_user.html" %}
{% load bootstrap %}
{% block title %}
{{ block.super }} - Reset Password 
{% endblock %}

{% block content %}
 <div class="container">
  {# checks if uidb36 and token are valid #}
  {% if validlink %} 
    <p> Enter a new password below.</p>
    <form action="{{ request.path }}"
        method="post">
    {% csrf token %}
    {{ form|bootstrap }}
    <button class="button-primary"
        type="submit">
      Save New Password</button>
    </form>
  {% else %}
    <p> This reset link is no longer valid.</p>
    <p> Please request a new reset mail. </p>
     <a href="{% url 'dj-auth:pw_reset_start' %}">
      here. </a></p>
  {% endif %}
 </div>
{% endblock %}

user/templates/user/password_reset_form.html
{% extends parent_template|default:"user/base_user.html" %}
{% load bootstrap %}
{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
<div class="container">
 <div class="center">
  <p> Reset your password by email.</p>
 </div>
 
 <form action="{% url 'dj-auth:pw_reset_start' %}"
    method="post">
   {% csrf_token %}
   {{ form|bootstrap }}
   <button type="submit">
    Send Me Reset Instructions </button>      
 </form>
</div>

{% endblock %}

user/templates/user/signup.html
{% extends parent_template|default:"user/base_user.html" %}
{% load bootstrap %}
{% block title %}
{{ block.super }} - Sign Up
{% endblock %}

{% block content %}
  <div class="container">
     <form action="{% url 'dj-auth:create' %}"
   method="post">
   {% csrf_token %}
    {{ form|bootstrap }}
    {% if next %}
      <input type="hidden" name="text" value="{{ next }}">
    {% endif %}
 <button type="submit">
  {{ login_button|default:'Sign Up' }}</button>
</form>
  </div>
{% endblock %}

user/templates/user/user_confirm_delete.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Disable Account
{% endblock %}

{% block content %}
  <div class="container">
     <p> Disable your account?</p>
     <p> This cannot be undone.</p> 
   <form action="{% url 'dj-auth;disable' %}"
        method="post">
    {% csrf_token %}
    <button type="submit"> 
     Disable Account</button>
   </form>
  </div>
  
  




{% endblock %}