prp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
import library.urls as library_urls
from user import urls as user_urls
from .views import redirect_root
from library.views import json

from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm


urlpatterns = [
  url(r'^$', redirect_root),
  url(r'^library/', include(library_urls)),
  url(r'^admin/', admin.site.urls),
  url(r'^index/$', json),
  url(r'^user/', include(user_urls, namespace='dj-auth')),
  


]

    

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .views import signup
app_name = 'user'

password_urls = [
    url(r'^change/$',
        auth_views.password_change,
        {'template_name': 'user/password_change_form.html',
        'post_change_redirect': reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name': 'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$', auth_views.password_reset,
        {'template_name': 
            'user/password_reset_form.html',
        'email_template_name':
            'user/password_reset_email.txt',
        'subject_template_name':
            'user/password_reset_subject.txt',
        'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
     url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'^reset/done/$',
        auth_views.password_reset_complete,
            {'template_name':
                'user/password_reset_complete.html',
            'extra_context':
                {'form': AuthenticationForm}},
            name='pw_reset_complete'),

]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    
    url(r'^login/$', auth_views.login,
        {'template_name': 'user/login.html'},
        name='login'),
    
   url(r'^logout/$',
        auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
        
    url(r'^password/', include(password_urls)),
    
    url(r'^create/$', signup,
        name='create'),
    
        
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <div>
        <title>
            {% block title %} Library {% endblock %}
        </title>
    </div>
    <style>
            * {
            box-sizing: border-box;
        }
        
        .bg-primary {
            background-color: #aaaa;
        }
        
        p {
            font-size: small;
        }
        
        body {
            font-size: 2.5em;
        }
        
        a {
            color: black;
            transition: 0.5s;
            display: block;
        }
        
        h4 {
            float: right;
            font-size: 1.25em;
            color: blue;
        }
        
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
            width: 21%;
            border-radius: 5px;
            margin: 18px;
            display: inline-block;
            padding: 16px;

        }
        
        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
        }
        
        img {
            padding: 12px;
        }
        
        .container {
            padding: 2px 16px;
        }
        
        .desc {
            padding: 16px 32px;
            font-size: small;
            span.glyphicon-link {
                font-size: 95%;
            }
            .clearfix::after {
                content: "";
                clear: both;
                display: table;
            }
    </style>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'library_book_list' %}">Library</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Books
                  <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'library_book_list' %}">All Books</a></li>
                        <li><a href="{% url 'library_create_book' %}">Add a Book</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories
                  <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'library_category_list' %}">All Categories</a></li>
                        <li><a href="{% url 'library_create_category' %}">Add a Category</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Authors
                  <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'library_author_list' %}">All Authors</a></li>
                        <li><a href="{% url 'library_author_create' %}">Add an Author</a></li>
                    </ul>
                </li>

                <li>
                    <form class="navbar-form" role="search" method="GET">
                        <input type="text" name="q" class="form-control" placeholder="Search">
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>

                </li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                <li>
                    <a href="{% url 'dj-auth:login' %}?next={{ request.path }}">
                        <span class="glyphicon glyphicon-log-in"></span> Login
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'dj-auth:logout' %}?next={{ request.path }}">
                        <span class="glyphicon glyphicon-log-in"></span> Log Out</a>
                </li>
                {% endif %}
                <li><a href="{% url 'dj-auth:create' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            </ul>
        </div>
    </nav>
    <main>
        {% block content %} Default {% endblock %}
    </main>
</body>

</html>